In [24]:
import pandas as pd
import matplotlib.pyplot as plt

In [25]:
path = '/Users/julia/Desktop/simplified_data.csv'
data = pd.read_csv(path)
data.head(10)

,action_name,leaf_value,effort_level,time,user_id,categories
0,Commute by leg power - walk or bike to work or...,1,Low,1739461726000,62002cce-0993-4658-b6dd-ec2b10bd3337,Transportation and Travel
1,Use your reusable water bottle every day this ...,1,Low,1739461761000,62002cce-0993-4658-b6dd-ec2b10bd3337,Around the House
2,Use reusable shopping bags this week,1,Low,1739461776000,62002cce-0993-4658-b6dd-ec2b10bd3337,Around the House
3,Recycle all your plastic and aluminum beverage...,1,Low,1739461789000,62002cce-0993-4658-b6dd-ec2b10bd3337,Recycling and Upcycling
4,Pack your leftovers in reusable containers thi...,1,Low,1739461836000,62002cce-0993-4658-b6dd-ec2b10bd3337,Around the House
5,Compost your food waste at home this week,1,Low,1739462048000,62002cce-0993-4658-b6dd-ec2b10bd3337,Food and Dining
6,Wash only full loads of laundry this week,1,Low,1743016298000,283fe88d-ce7f-4f3f-9786-5f05c2b53754,Around the House
7,Switch one standard bulb to LED lights,10,Med,1743016307000,283fe88d-ce7f-4f3f-9786-5f05c2b53754,Energy Efficiency
8,Sell or donate your old clothing and accessori...,2,Low,1743016327000,283fe88d-ce7f-4f3f-9786-5f05c2b53754,Recycling and Upcycling
9,Sell or donate your old books this year,2,Low,1743016343000,283fe88d-ce7f-4f3f-9786-5f05c2b53754,Recycling and Upcycling

In [26]:
most_frequent_leaf = data.groupby('user_id')['leaf_value'].agg(lambda x: x.mode()[0]).reset_index()
most_frequent_leaf.columns = ['user_id', 'most_frequent_leaf_value']
most_frequent_leaf

                                 user_id  most_frequent_leaf_value
0   03a7ff0b-ce38-4604-a405-2fce519db55e                         1
1   0c1b7c00-a93a-4169-8c9c-a88f7fee7655                         1
2   15455af3-cc0a-45cf-b8c4-f8d301e46c1e                         1
3   159270b8-5b3d-4a9a-9fed-4e1c11e62601                         1
4   1830b58e-7968-4161-b2aa-2bd37ecd907d                         1
..                                   ...                       ...
95  f708a0b9-3ff2-466b-b825-ec4d0c0f4e18                         1
96  fbce9840-2fec-4fef-9f00-235791252538                         2
97  fe199b58-5da8-42d3-ae66-8ee241f73f4c                         1
98  fe1e550a-3788-4c08-940c-9ffcb6e9724c                         1
99  ff09205c-0242-40ae-a849-784789b4ba88                         1

[100 rows x 2 columns]

In [27]:
most_frequent_action = data.groupby('user_id')['action_name'].agg(lambda x: x.mode()[0]).reset_index()
most_frequent_action.columns = ['user_id', 'most_frequent_action']
most_frequent_action

,user_id,most_frequent_action
0,03a7ff0b-ce38-4604-a405-2fce519db55e,Buy second-hand clothes
1,0c1b7c00-a93a-4169-8c9c-a88f7fee7655,A day without meat
2,15455af3-cc0a-45cf-b8c4-f8d301e46c1e,Check out the school Vivarium
3,159270b8-5b3d-4a9a-9fed-4e1c11e62601,Get familiar with your utility bill this month
4,1830b58e-7968-4161-b2aa-2bd37ecd907d,Close your curtains or blinds this week
...,...,...
95,f708a0b9-3ff2-466b-b825-ec4d0c0f4e18,Use your reusable water bottle every day this ...
96,fbce9840-2fec-4fef-9f00-235791252538,Use wool dryer balls in your dryer this month
97,fe199b58-5da8-42d3-ae66-8ee241f73f4c,Follow GetGreen on Social Media
98,fe1e550a-3788-4c08-940c-9ffcb6e9724c,Turn off the lights when not in use this week
99,ff09205c-0242-40ae-a849-784789b4ba88,Buy gifts from local vendors

In [28]:
most_frequent_cat = data.groupby('user_id')['categories'].agg(lambda x: x.mode()[0]).reset_index()
most_frequent_cat.columns = ['user_id', 'most_frequent_category']
most_frequent_cat

                                 user_id most_frequent_category
0   03a7ff0b-ce38-4604-a405-2fce519db55e        Food and Dining
1   0c1b7c00-a93a-4169-8c9c-a88f7fee7655       Around the House
2   15455af3-cc0a-45cf-b8c4-f8d301e46c1e       Around the House
3   159270b8-5b3d-4a9a-9fed-4e1c11e62601       Around the House
4   1830b58e-7968-4161-b2aa-2bd37ecd907d       Around the House
..                                   ...                    ...
95  f708a0b9-3ff2-466b-b825-ec4d0c0f4e18       Around the House
96  fbce9840-2fec-4fef-9f00-235791252538       Around the House
97  fe199b58-5da8-42d3-ae66-8ee241f73f4c       Around the House
98  fe1e550a-3788-4c08-940c-9ffcb6e9724c       Around the House
99  ff09205c-0242-40ae-a849-784789b4ba88    Health and Wellness

[100 rows x 2 columns]

In [29]:
most_frequent_effort = data.groupby('user_id')['effort_level'].agg(lambda x: x.mode()[0]).reset_index()
most_frequent_effort.columns = ['user_id', 'most_frequent_effort_level']
most_frequent_effort

                                 user_id most_frequent_effort_level
0   03a7ff0b-ce38-4604-a405-2fce519db55e                        Low
1   0c1b7c00-a93a-4169-8c9c-a88f7fee7655                        Low
2   15455af3-cc0a-45cf-b8c4-f8d301e46c1e                        Low
3   159270b8-5b3d-4a9a-9fed-4e1c11e62601                        Low
4   1830b58e-7968-4161-b2aa-2bd37ecd907d                        Low
..                                   ...                        ...
95  f708a0b9-3ff2-466b-b825-ec4d0c0f4e18                        Low
96  fbce9840-2fec-4fef-9f00-235791252538                        Low
97  fe199b58-5da8-42d3-ae66-8ee241f73f4c                        Low
98  fe1e550a-3788-4c08-940c-9ffcb6e9724c                        Low
99  ff09205c-0242-40ae-a849-784789b4ba88                        Low

[100 rows x 2 columns]

In [31]:
data['time'] = pd.to_datetime(data['time'])
data['time']

0      1970-01-01 00:28:59.461726
1      1970-01-01 00:28:59.461761
2      1970-01-01 00:28:59.461776
3      1970-01-01 00:28:59.461789
4      1970-01-01 00:28:59.461836
                  ...
1723   1970-01-01 00:29:05.858061
1724   1970-01-01 00:29:05.858094
1725   1970-01-01 00:29:05.858109
1726   1970-01-01 00:29:05.858172
1727   1970-01-01 00:29:05.858184
Name: time, Length: 1728, dtype: datetime64[ns]

In [41]:
data['date_only'] = data['time'].dt.date
data['time_only'] = data['time'].dt.time

In [42]:
data.head()

,action_name,leaf_value,effort_level,time,user_id,categories,date_only,time_only,hour
0,Commute by leg power - walk or bike to work or...,1,Low,1970-01-01 00:28:59.461726,62002cce-0993-4658-b6dd-ec2b10bd3337,Transportation and Travel,1970-01-01,00:28:59.461726,0
1,Use your reusable water bottle every day this ...,1,Low,1970-01-01 00:28:59.461761,62002cce-0993-4658-b6dd-ec2b10bd3337,Around the House,1970-01-01,00:28:59.461761,0
2,Use reusable shopping bags this week,1,Low,1970-01-01 00:28:59.461776,62002cce-0993-4658-b6dd-ec2b10bd3337,Around the House,1970-01-01,00:28:59.461776,0
3,Recycle all your plastic and aluminum beverage...,1,Low,1970-01-01 00:28:59.461789,62002cce-0993-4658-b6dd-ec2b10bd3337,Recycling and Upcycling,1970-01-01,00:28:59.461789,0
4,Pack your leftovers in reusable containers thi...,1,Low,1970-01-01 00:28:59.461836,62002cce-0993-4658-b6dd-ec2b10bd3337,Around the House,1970-01-01,00:28:59.461836,0

In [ ]:
import os
print(os.getcwd())